comics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pcomic.urls', namespace='pcomic'))
]
urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

pcomic/urls.py
from django.urls import path
from .views import home_view, tagged, detail_view, category, Comics_view, comics_search

app_name = 'pcomics'

urlpatterns=[
    path('', home_view, name='home'),
    path('search/', comics_search, name='comics-search'),
    path('comics/', Comics_view.as_view() , name='comics'),
    path('gallary/<slug>/', detail_view, name='detail'),
    path('gallary/tag/<slug>/', tagged, name='tags'),
    path('gallary/category/<str:cats>/', category, name='category')
]

pcomic/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager
from django.shortcuts import reverse
from PIL import Image

class Category(models.Model):
    name = models.CharField(max_length=100) 

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=150)
    tags = TaggableManager()
    main_image = models.FileField(blank=True)
    slug = models.SlugField(unique=True, max_length=100)
    date_updated = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
  
    def __str__(self):
        return self.title 
 
    def get_absolute_url(self):
        return reverse("pcomic:tags", kwargs={
            'slug': self.slug
        })

    def save(self):
        super().save()  # saving image first

        img = Image.open(self.main_image.path) # Open image using self

        if img.height > 300 or img.width > 300:
            new_img = (300, 300)
            img.thumbnail(new_img)
            img.save(self.main_image.path) 
  
  
class PostImage(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    images = models.FileField()

    def __str__(self):
        return self.post.title

pcomic/forms.py
from django import forms
from . models import Post

class PostSearchForm(forms.Form):
    q = forms.CharField()

pcomic/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from.models import Post, PostImage, Category
from taggit.models import Tag
from .forms import PostSearchForm

def home_view(request):
    posts = Post.objects.all().order_by('-date_updated')[:4]
    # Show most common tags 
    common_tags = Post.tags.most_common()
    context = {
        'posts':posts,
        'common_tags':common_tags,
    }
    return render(request, 'home.html', context)

class Comics_view(ListView):
    model = Post
    paginate_by = 3
    template_name = 'comics.html'

def detail_view(request, slug):
    post = get_object_or_404(Post, slug=slug)
    photos = PostImage.objects.filter(post=post)
    related = Post.objects.filter(category=post.category).exclude(id=post.id)

    return render(request, 'detail.html', {
        'post':post,
        'photos':photos,
        'related': related
    })

def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    posts = Post.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'posts': posts,
    }
    return render(request, 'tag.html', context)

def category(request, cats):
    category = get_object_or_404(Category, name=cats.replace('-', ' ').upper())
    posts = Post.objects.filter(category=category)
    context = {
        'posts': posts
    }
    return render(request, 'category.html', context)


def comics_search(request):
    form = PostSearchForm()
    q = '' 
    results = []

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            results = Post.objects.filter(title__contains=q)


    return render(request, 'search.html', 
                        {'form': form,
                        'q': q,
                        'results':results})

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    {% block link %}
    {% endblock %}
    <title>Comics</title>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container">
    {% block content %}
    {% endblock %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% block js %}
    {% endblock %}
    {% include "footer.html" %}
  </body>
</html>

templates/category.html
{% extends "base.html" %}
{% load static %}
{% block link %}
 <link href="{% static 'css/comic.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="container">
    {% for post in posts %}
    <ul>
      <li class="li">
      <a href="{% url 'pcomics:detail' post.slug %}"><img class="image" src="{{post.main_image.url}}"><a href="{% url 'pcomics:category' post.category|slugify %}"><p class="p">{{post.category}}</p></a></a>
         <div class="title">{{post.title|capfirst}}</div>
         <div class="date"><p>{{post.date_updated}}</p></div>
      </li>
    </ul>
    {% endfor %}
  </div>
{% endblock %}

templates/comics.html
{% extends "base.html" %}
{% load static %}
{% block link %}
 <link href="{% static 'css/comic.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="container">
    {% for post in object_list %}
    <ul>
      <li class="li">
      <a href="{% url 'pcomics:detail' post.slug %}"><img class="image" src="{{post.main_image.url}}"><a href="{% url 'pcomics:category' post.category|slugify %}"><p class="p">{{post.category}}</p></a></a>
         <div class="title">{{post.title|capfirst}}</div>
         <div class="date"><p>{{post.date_updated}}</p></div>
      </li>
    </ul>
    {% endfor %}

</div> 
{% for contact in page_obj %}
    {{ contact.full_name|upper }}<br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/detail.html
{% extends "base.html" %}
{%  load static %}
{% block link %}
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link href="{% static 'css/detail.css' %}" rel="stylesheet">
  <link href="{% static 'css/jquery.fancybox.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="gallary">
{% for p in photos %}
  <a href="{{p.images.url}}" data-fancybox="group" data-caption="{{p.images.id}}"><img src="{{p.images.url}}"></a>
{% endfor %}
</div>
{% block js %}
<script type="text/javascript" src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
{% endblock %}
<div class="rel">
<h2>Related Comics:</h2>
{% if related %}
{% for relative in related %}
<a href="{% url 'pcomics:detail' relative.slug %}"><p>{{relative}}</p></a>
{% endfor %}
{%else%}
<div>No Related Comics available for this Comic!</div>
{%endif%}
</div>
<div class="t">
<h2>Tags:</h2>
{% for tags in post.tags.all %}
<a href="{% url 'pcomics:tags' tags.slug %}"><div class="tags">{{tags}}</div></a>
{% endfor %}
</div>
{% endblock %}

templates/footer.html
{% comment %} <!-- Footer -->
<footer class="page-footer font-small blue">
  
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
  
  {% for tags in common_tags %}
    <div class="card-body">
        <a href="{% url 'pcomics:tags' tags.slug %}"><p class="card-text">{{tags}}</p></a>
    </div>
  {%endfor%}
</footer>
<!-- Footer --> {% endcomment %}

templates/home.html
{% extends "base.html" %}
{%  load static %}
{% block link %}
 <link href="{% static 'css/main.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="container">
  <div class="comics-page"><a href="{% url 'pcomics:comics' %}"><img class="icon" src="media/icon.png">GO TO COMICS PAGE</a></div>
  <h1 class="title-1">Latest and Updated Comics</h1>
    <hr class="hr">
    {% for post in posts %}
    <ul>
      <li>
      <a href="{% url 'pcomics:detail' post.slug %}"><img class="image" src="{{post.main_image.url}}"></a>
       <div class="title">{{post.title|capfirst}}</div>
      </li>
    </ul>
    {% endfor %}
{% endblock %}

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Somehow I got an error, so I comment the title, just uncomment to show -->
    <!-- <title>Responsive Navbar with Searchbox</title> --> 
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
  </head>
  <body>
    <nav>
      <ul>
<li class="logo"><a href="{% url 'pcomics:home' %}">BESTCOMIX4KIDS</a></li>

<form method="get" action="/search/" method="get">
    <li class="search-icon">
        <input type="search" name="q" placeholder="Search">               
        <label class="icon">
            <span><button class="fas fa-search" type="submit"></button><span>
        </label>
   </li>
</form>

</ul>
</nav>
<script>
      $('nav ul li.btn span').click(function(){
        $('nav ul div.items').toggleClass("show");
        $('nav ul li.btn span').toggleClass("show");
      });
    </script>
  </body>
</html>
<div class="heading">
    <h2>BESTCOMIX4KIDS.com</h2>
</div>

templates/search.html
{% extends "base.html" %}
{% load static %}
{% block link %}
 <link href="{% static 'css/comic.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="container">
    {% for post in results %}
    <ul>
      <li class="li">
      <a href="{% url 'pcomics:detail' post.slug %}"><img class="image" src="{{post.main_image.url}}"><a href="{% url 'pcomics:category' post.category|slugify %}"><p class="p">{{post.category}}</p></a></a>
         <div class="title">{{post.title|capfirst}}</div>
         <div class="date"><p>{{post.date_updated}}</p></div>
      </li>
    </ul>
    {% endfor %}

</div> 
{% for contact in page_obj %}
    {{ contact.full_name|upper }}<br>
{% endfor %}
{% if pagination %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

templates/tag.html
{% extends "base.html" %}
{% load static %}
{% block link %}
 <link href="{% static 'css/comic.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="container">
    {% for post in posts %}
    <ul>
      <li class="li">
      <a href="{% url 'pcomics:detail' post.slug %}"><img class="image" src="{{post.main_image.url}}"><a href="{% url 'pcomics:category' post.category|slugify %}"><p class="p">{{post.category}}</p></a></a>
         <div class="title">{{post.title|capfirst}}</div>
         <div class="date"><p>{{post.date_updated}}</p></div>
      </li>
    </ul>
    {% endfor %}
  </div>
{% endblock %}